# Prettier Configuration File

# https://prettier.io/docs/en/configuration.html

arrowParens: avoid
bracketSpacing: false
endOfLine: lf
htmlWhitespaceSensitivity: css
printWidth: 120
proseWrap: preserve
requirePragma: false
semi: true
singleQuote: true
tabWidth: 2
trailingComma: all
useTabs: false
vueIndentScriptAndStyle: true
xmlSelfClosingSpace: false
xmlWhitespaceSensitivity: strict

# Override configuration for certain files
overrides:
  - files: '*.json'
    options:
      printWidth: 200
  - files: '*.xml'
    options:
      printWidth: 80
  - files: strings-*.xml
    options:
      printWidth: 100
  - files: '*.xsl'
    options:
      parser: xml

plugins:
  - '@prettier/plugin-xml'
