name: CI
'on':
  push:
    branches:
      - master
      - develop
  workflow_dispatch:
jobs:
  build-dita:
    name: Build DITA
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Build Bootstrap
        uses: dita-ot/dita-ot-action@master
        with:
          install: |
            apt-get update -q
            export DEBIAN_FRONTEND=noninteractive
            apt-get install -qy --no-install-recommends nodejs
            nodejs -v
          plugins: |
            fox.jason.extend.css
            https://github.com/infotexture/dita-bootstrap/archive/develop.zip
            fox.jason.prismjs
            fox.jason.favicon
          project: .github/dita-ot/html.xml
      - name: Deploy HTML 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: out/html # The folder the action should deploy.
