name: CI
'on':
  push:
    branches:
      - master
      - develop
  workflow_dispatch:
jobs:
  build-dita:
    name: Build DITA
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Build Bootstrap
        uses: dita-ot/dita-ot-action@master
        with:
          install: |
            apt-get update -q
            export DEBIAN_FRONTEND=noninteractive
            apt-get install -qy --no-install-recommends nodejs
            nodejs -v
          plugins: |
            fox.jason.extend.css
            https://github.com/infotexture/dita-bootstrap/archive/develop.zip
            https://github.com/jason-fox/fox.jason.prismjs/archive/master.zip
            fox.jason.favicon
            https://github.com/jason-fox/fox.jason.open-graph/archive/master.zip
          project: .github/dita-ot/html.xml
      - name: Deploy HTML 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: out/html # The folder the action should deploy.
          commit-message: '🚀 Deploy infotexture/dita-bootstrap@${{GITHUB_SHA:0:7}} to GitHub Pages'
          git-config-name: 'GitHub Action'
          git-config-email: 'action@github.com'
